### ISSUE TITLE
Research Plan

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#22]
This part of the work should be done by Opeyemi Ayobami and Temitope Emmanuel

**Comment by Sun-base** [comment]
Work completed. Link attached below
https://docs.google.com/document/d/1Suhnx-jSaxXlugG2bPch6hEjTDkzlwjIjaoAMe0QTnI/edit?usp=drivesdk

**Comment by Temitopeemma** [comment]
I'm glad I could do this. It expounded my knowledge gap. I never knew anything about Animation Library. 

Thank you Zuri. Thank you Team 91.

**Comment by Opelobami** [comment]
Temitope is fun to work with. A great cheerleader and always ahead to make the work easier. Such a great team member to work with

**Comment by Temitopeemma** [comment]
Coming up with a research plan in a field I never knew existed was quite a means of exploring. It filled my knowledge gap and I'm glad to know this would help so many developers & designers.
