### ISSUE TITLE
Dashboard Menu

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#24]
This task is to be completed by Oluwaseun Lawal and Opeyemi Ayobami

**Comment by Sun-base** [comment]
Task completed. Link attached below
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=174%3A206

**Comment by Sun-base** [comment]
Task completed. Link attached below
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=174%3A206

**Comment by Opelobami** [comment]
When I inputted animations on the design, it was static and I thought it wasn't working untill I spoke with brainiac about it.

It was him who told me it worked when presented. I learnt a new thing there

**Comment by Opelobami** [comment]
I enjoyed designing the dashboard page. It was my first time inputting animations on designs.
