### ISSUE TITLE
Search Results Page

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#25]
This part is to be handled by Amanda Oli and Oluwaseun Lawal

**Comment by Sun-base** [comment]
Task completed. Link attached below
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=174%3A206

**Comment by Sun-base** [comment]
Together with Amanda Oli, we build a search Result page that shows the result of searches run by users on the home page. It was a quite organized design and it was submitted to the developers for implementation afterwards

**Comment by amandaoli** [comment]
@Sun-base and I worked on designing the search result page.
