### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#30]
This part is to be done by Amanda Oli

**Comment by Sun-base** [comment]
Task completed. Link attached below
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=174%3A206

**Comment by amandaoli** [comment]
For this task, I designed the headers for unauthenticated and authenticated users. Also, I designed the footer which was to be used across the app. 

PS: After initial completion of this task, I worked with Brainiac and Jeremiah as they reworked the Footer following requests from the developers to have a simpler design to work with.

**Comment by Mojezcr8tiv** [comment]
Based on developers request, I made some adjustment on the header.
