### ISSUE TITLE
Upload Images, Illustrations, Icon and Logo on Google Drive for easy accessibility for Developers 

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#33]
Everyone is expected to upload all the images, Illustrations, Icon and Logo used in their designs on Google Drive so that developers can access it easily in the course of their work. Upload to the link below

 https://drive.google.com/drive/folders/1KoNzTUJEDxW4r9HUKsT1QtvIkRUGeOMy

**Comment by Opelobami** [comment]
Guess we're all done with this

**Comment by Enigmas01** [comment]
Yes, I think. It should be marked as complete.

**Comment by AladeYunus** [comment]
The images, Illustrations, Icon and Logo used on the animation page have all been uploaded on the Google drive link.

**Comment by Mojezcr8tiv** [comment]
all images have been uploaded.

**Comment by eseohe4** [comment]
Ilustrations used on the login / Signup page has been uploaded

**Comment by eseohe4** [comment]
Illustrations used on the Login/Signup page has been uploaded

**Comment by Sun-base** [comment]
I assigned this particular task to every team member so that we can have a repository for all the components we used in our designers. This will help developers link those components to their work and ensure ease of accessibility. Everyone did their part of the work and we handed over to the developers.
