### ISSUE TITLE
Terms and Conditions/Policy Page

### ISSUE THREAD

**Issue by Sun-base** [zuri-training/anima_lib_team-91#39]
This part is to be done by Oluwaseun Lawal and Brainiac Williams

**Comment by Enigmas01** [comment]
This is already done with, both Lo-Fi and Hi-Fi screen. Should be closed now.

**Comment by Sun-base** [comment]
Together with with Brainiac Williams, I created a structure for the Terms and Conditions for our project, while we also had Policy information. We generated this using an AI powered web platform and we were able to tailor this to our own project. The contents were added to the design and submitted to the developers for production afterwards.
