### ISSUE TITLE
Team page design

### ISSUE THREAD

**Issue by Mojezcr8tiv** [zuri-training/anima_lib_team-91#44]
if you are yet to  upload your image on the drive, please do asap

**Comment by eseohe4** [comment]
Done

**Comment by Mojezcr8tiv** [comment]
Design done. Only 4 team members whose photo was not uploaded before the deadline for design link submittion has their pictures absent from the team page design.

**Comment by Mojezcr8tiv** [comment]
Fixed.

**Comment by Mojezcr8tiv** [comment]
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=167%3A1368
Here is the link to the library and team page

**Comment by Mojezcr8tiv** [comment]
link to team frame

https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=1345%3A4294

**Comment by Mojezcr8tiv** [comment]
link to library frame
https://www.figma.com/file/7KC7ZQMjTujDu1qgyaUnxw/StyleFlow-Project?node-id=367%3A1901
